// Copyright(c) 2018 Seth Ballantyne <seth.ballantyne@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this
// software and associated documentation files(the "Software"), to deal in the Software
// without restriction, including without limitation the rights to use, copy, modify, merge,
// publish, distribute, sublicense, and / or sell copies of the Software, and to permit persons
// to whom the Software is furnished to do so, subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
// FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
// OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#pragma once

using namespace System;

/// <summary>
/// Represents an error condition generated by a Win32 API function.
/// </summary>
public ref class Win32Exception : public Exception
{
public:
    Win32Exception() : Exception() {}
    Win32Exception(String ^message) : Exception(message) {}

    /// <summary>
    /// Uses the Win32 API function GetLastError() to build an error string detailing why
    /// <i>function</i> failed.
    /// </summary>
    /// <param name="function">the Win32 API function that failed.</param>
    /// <returns>A managed string containing the formatted error message.</returns>
    /// <exception cref="System::ArgumentNullException"><i>function</i> is <b>null</b>.</exception>
    static String ^Format(String ^function);
};