// Copyright(c) 2018 Seth Ballantyne <seth.ballantyne@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this
// software and associated documentation files(the "Software"), to deal in the Software
// without restriction, including without limitation the rights to use, copy, modify, merge,
// publish, distribute, sublicense, and / or sell copies of the Software, and to permit persons
// to whom the Software is furnished to do so, subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
// FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
// OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#pragma once

#include <dinput.h>
#include "logmanager.h"
#include "logtype.h"

using namespace System;

/// <summary>
/// encapsulates a snapshot of the mouse state. There's functionality missing 
/// (like ButtonUp or ButtonClick functions) because the game doesn't need them.
/// </summary>
public ref class Mouse
{
private:
    int x;
	int y;
	int z;

	array<byte, 1> ^buttons = gcnew array<byte, 1>(8);
public:
    /// <summary>
    /// Creates a new instance of Mouse.
    /// </summary>
    /// <param name="mouseState">the instance of LPDIMOUSESTATE2 generated by Input.</param>
    /// <exception cref="System::ArgumentNullException"><i>mouseState</i> is <b>null</b>.</exception>
    Mouse(LPDIMOUSESTATE2 mouseState2)
    {
        if(mouseState2 == NULL)
        {
            throw gcnew ArgumentNullException("mouseState");
        }
        else
        {
            this->x = mouseState2->lX;
			this->y = mouseState2->lY;
			this->z = mouseState2->lZ;

			for(int i = 0; i < 8; i++)
			{
				buttons[i] = mouseState2->rgbButtons[i];
			}	
        }
    }

    /// <summary>
    /// returns true if the specified button is currently pressed down.
    /// </summary>
    /// <param name="button">the buttons DirectInput scancode. (DIK_*)</param>
    /// <returns></returns>
    bool ButtonDown(BYTE button)
    {
        //return mouseState->rgbButtons[button] & 0x80;
		return buttons[button] & 0x80;
    }

    /// <summary>
    /// returns the X position of the mouse.
    /// </summary>
    property int X
    {
        int get()
		{
            return x;
        }
    }

    /// <summary>
    /// returns the Y position of the mouse.
    /// </summary>
    property int Y
    {
        int get()
        {
            return y;
        }
    }
};
